language: python
python:
  - "3.6"
before_install:
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov="./"
after_success:
  - codecov # submit coverage